# Generated by Django 5.0.4 on 2024-05-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_buy', '0003_alter_order_options_alter_order_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
