# Generated by Django 5.0.4 on 2024-05-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_buy', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
    ]
