# Generated by Django 5.0.4 on 2024-05-25 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0009_delete_booking'),
        ('ticket_buy', '0005_alter_order_order_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата и время бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ticket',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='poster.ticket', verbose_name='Билет'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата и время заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='poster.ticket', verbose_name='Билет'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
