# Generated by Django 5.0.4 on 2024-05-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hall_part',
            new_name='Hall_sector',
        ),
        migrations.AlterModelOptions(
            name='hall_sector',
            options={'verbose_name': 'Сектор зала', 'verbose_name_plural': 'Сектор зала'},
        ),
        migrations.AlterModelOptions(
            name='theater',
            options={'verbose_name': 'Театра', 'verbose_name_plural': 'Театры'},
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='hall_part',
            new_name='hall_sector',
        ),
    ]
