# Generated by Django 5.0.4 on 2024-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_info', '0004_hall_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='served',
            field=models.BooleanField(default=True, verbose_name='Обслуживается'),
        ),
    ]
