# Generated by Django 5.0.4 on 2024-05-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_info', '0006_social_media_theater_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theater',
            name='social_media',
        ),
        migrations.AddField(
            model_name='theater',
            name='social_media',
            field=models.ManyToManyField(null=True, to='theater_info.social_media', verbose_name='Социальные сети'),
        ),
    ]
