# Generated by Django 5.0.4 on 2024-05-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_info', '0007_remove_theater_social_media_theater_social_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AlterField(
            model_name='theater',
            name='social_media',
            field=models.ManyToManyField(blank=True, to='theater_info.social_media', verbose_name='Социальные сети'),
        ),
        migrations.CreateModel(
            name='Troupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(null=True, upload_to='directors/', verbose_name='Портрет')),
                ('position', models.ManyToManyField(to='theater_info.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Труппа',
                'verbose_name_plural': 'Труппа',
            },
        ),
    ]
