# Generated by Django 5.0.4 on 2024-05-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_info', '0008_position_alter_theater_social_media_troupe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hall_sector',
            new_name='HallSector',
        ),
        migrations.RenameModel(
            old_name='Social_media',
            new_name='SocialMedia',
        ),
        migrations.RemoveField(
            model_name='troupe',
            name='position',
        ),
        migrations.AddField(
            model_name='troupe',
            name='title',
            field=models.CharField(default=2, max_length=100, verbose_name='Звание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='troupe',
            name='image',
            field=models.ImageField(null=True, upload_to='troupe/', verbose_name='Портрет'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
