# Generated by Django 5.0.4 on 2024-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_info', '0009_rename_hall_sector_hallsector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='troupe',
            name='actor',
            field=models.BooleanField(default=False, verbose_name='Актер'),
        ),
        migrations.AddField(
            model_name='troupe',
            name='art_group',
            field=models.BooleanField(default=False, verbose_name='Художественное руководство'),
        ),
    ]
