# Generated by Django 5.0.4 on 2024-05-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('poster', '0010_alter_session_options_alter_performance_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTimeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('total_tickets', models.IntegerField(verbose_name='Общее количество билетов')),
                ('sold_tickets', models.IntegerField(verbose_name='Проданные билеты')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доход')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.RenameModel(
            old_name='DailyStatistics',
            new_name='DailyPerformanceStatistics',
        ),
    ]
