# Generated by Django 5.0.4 on 2024-05-10 08:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('theater_info', '0008_position_alter_theater_social_media_troupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(db_index=True, max_length=50, primary_key=True, serialize=False, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='performances/', verbose_name='Постер')),
                ('premiere', models.BooleanField(default=False, verbose_name='Премьера')),
                ('duration', models.DurationField(verbose_name='Продолжительность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания')),
                ('repertoire', models.BooleanField(default=False, verbose_name='В репертуаре')),
                ('url', models.SlugField(unique=True)),
                ('actors', models.ManyToManyField(related_name='performances_as_actor', to='theater_info.troupe', verbose_name='Актеры')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances_as_director', to='theater_info.troupe', verbose_name='Постановщик')),
                ('genre', models.ManyToManyField(to='poster.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Спектакль',
                'verbose_name_plural': 'Спектакли',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('price_percentage_increase', models.IntegerField(default=0, help_text='Укажите процентное увеличение цены(например 10)', validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Процентное увеличение цены')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater_info.hall', verbose_name='Зал')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster.performance', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold', models.BooleanField(default=False, verbose_name='Продан')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater_info.seat', verbose_name='Сиденье')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster.session', verbose_name='Сеанс')),
            ],
            options={
                'verbose_name': 'Билет',
                'verbose_name_plural': 'Билеты',
            },
        ),
    ]
