# Generated by Django 5.0.4 on 2024-05-10 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
        ('theater_info', '0009_rename_hall_sector_hallsector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Обязанность в спектакле')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Обязанность в спектакле',
                'verbose_name_plural': 'Обязанности в спектактях',
            },
        ),
        migrations.RemoveField(
            model_name='performance',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='director',
        ),
        migrations.CreateModel(
            name='PositionExecutorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater_info.troupe', verbose_name='Исполнитель')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster.position', verbose_name='Обязанность в спектакле')),
            ],
            options={
                'verbose_name': 'Обязанность-исполнитель',
                'verbose_name_plural': 'Обязанности-исполнители',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='art_group',
            field=models.ManyToManyField(related_name='performances_as_art_group', to='poster.positionexecutorlink', verbose_name='Художественная группа'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater_info.troupe', verbose_name='Актёр')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='roles',
            field=models.ManyToManyField(related_name='performances_as_roles', to='poster.role', verbose_name='Роли'),
        ),
    ]
