# Generated by Django 5.0.4 on 2024-05-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_position_remove_performance_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionexecutorlink',
            name='executor',
            field=models.TextField(max_length=200, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='role',
            name='actor',
            field=models.TextField(max_length=200, verbose_name='Актёр'),
        ),
    ]
