# Generated by Django 5.0.4 on 2024-05-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0003_alter_positionexecutorlink_executor_alter_role_actor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='roles',
        ),
        migrations.AddField(
            model_name='performance',
            name='roles',
            field=models.TextField(default=1, verbose_name='Роли'),
            preserve_default=False,
        ),
    ]
