# Generated by Django 5.0.4 on 2024-05-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0004_remove_performance_roles_performance_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='url',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
