# Generated by Django 5.0.4 on 2024-05-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0005_alter_performance_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='age_restrictions',
            field=models.IntegerField(default=12, help_text='Age restriction in years (e.g.,0, 6, 12, 16, 18)'),
        ),
    ]
