# Generated by Django 5.0.4 on 2024-05-23 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0006_performance_age_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reserved',
            field=models.BooleanField(default=False, verbose_name='Забронирован'),
        ),
        migrations.AlterField(
            model_name='session',
            name='performance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poster.performance', verbose_name='Спектакль'),
        ),
    ]
