# Generated by Django 5.0.4 on 2024-05-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0008_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
