# Generated by Django 5.0.4 on 2024-05-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0009_delete_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ('-date',), 'verbose_name': 'Сеанс', 'verbose_name_plural': 'Сеансы'},
        ),
        migrations.AlterField(
            model_name='performance',
            name='url',
            field=models.SlugField(default='', unique=True),
        ),
    ]
